version: "3.8"

services:
    jupyter:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile
        ports:
            - "8888:8888"
        volumes:
            - ../notebooks:/home/jovyan/work