name: jupyter_tutorial_ges_disc
channels:
  - conda-forge
  - defaults
dependencies:
  - conda=4.9.0
  - python=3.8
  - jupyterlab=2.2.8
  - jupyterhub=1.1.0
  - notebook=6.1.4
  - protobuf=3.13
  - widgetsnbextension=3.5
  - sqlalchemy=1.3
  - conda-forge::blas[build=openblas]
  - statsmodels=0.12
  - h5py=2.10
  - intake
  - ipywidgets=7.5
  - bokeh=2.2
  - pytables=3.6
  - numba=0.51
  - patsy=0.5
  - dask=2.30
  - cython=0.29
  - scikit-image=0.17
  - matplotlib-base=3.3
  - cloudpickle=1.6
  - scikit-learn=0.23
  - sympy=1.6
  - vincent=0.4
  - xlrd=1.2
  - dill=0.3
  - beautifulsoup4=4.9
  - numexpr=2.7
  - xarray
  - intake-xarray
  - bottleneck=1.3
  - ipympl=0.5
  - scipy=1.5
  - pandas=1.1
  - seaborn=0.11
  - cartopy
